#pragma once

#define BuiltInCubeUserMesh							L"../BuiltIn/Cube.usermesh"
#define BuiltInSphereUserMesh						L"../BuiltIn/Sphere.usermesh"
#define BuiltInCyilinderUserMesh					L"../BuiltIn/Cyilinder.usermesh"
#define BuiltInQuadUserMesh							L"../BuiltIn/QuadUserMesh.mesh"
#define BuiltInQuadForwardUserMesh					L"../BuiltIn/QuadForwardUserMesh.mesh"
#define BuiltInQuadTopUserMesh						L"../BuiltIn/QuadTopUserMesh.mesh"
#define BuiltInQuadRightUserMesh					L"../BuiltIn/QuadRightUserMesh.mesh"
#define BuiltInCapsuleUserMesh						L"../BuiltIn/CapsuleUserMesh.mesh"
#define BuiltInRightTriangleUserMesh				L"../BuiltIn/RightTriangleUserMesh.mesh"
#define BuiltInTriangleUserMesh						L"../BuiltIn/TriangleUserMesh.mesh"
#define BuiltInRightTriangleEmptySideUserMesh		L"../BuiltIn/RightTriangleEmptySideUserMesh.mesh"
#define BuiltInRightTriangleBackSideUserMesh		L"../BuiltIn/RightTriangleBackSideUserMesh.mesh"
#define BuiltInRightTriangleFrontSideUserMesh		L"../BuiltIn/RightTriangleFrontSideUserMesh.mesh"

#define BuiltInWhiteTexture							L"../BuiltIn/WhiteTexture.png"
#define BuiltInBlackTexture							L"../BuiltIn/BlackTexture.png"
#define BuiltInRedTexture							L"../BuiltIn/RedTexture.png"
#define BuiltInGreenTexture							L"../BuiltIn/GreenTexture.png"
#define BuiltInBlueTexture							L"../BuiltIn/BlueTexture.png"
#define BuiltInTransparentWhiteTexture				L"../BuiltIn/TransparentWhiteTexture.png"
#define BuiltInTransparentBlackTexture				L"../BuiltIn/TransparentBlackTexture.png"
#define BuiltInTransparentRedTexture				L"../BuiltIn/TransparentRedTexture.png"
#define BuiltInTransparentGreenTexture				L"../BuiltIn/TransparentGreenTexture.png"
#define BuiltInTransparentBlueTexture				L"../BuiltIn/TransparentBlueTexture.png"

#define BuiltInBackgroundMaterial					L"../BuiltIn/BackgroundMaterial.material"
#define BuiltInSkyboxBackgroundMaterial				L"../BuiltIn/SkyboxBackgroundMaterial.material"
#define BuiltInPriorityMaterial						L"../BuiltIn/PriorityGeometryMaterial.material"
#define BuiltInNolightPriorityMaterial				L"../BuiltIn/NolightPriorityGeometryMaterial.material"
#define BuiltInGeometryMaterial						L"../BuiltIn/GeometryMaterial.material"
#define BuiltInNolightGeometryMaterial				L"../BuiltIn/NolightGeometryMaterial.material"
#define BuiltInNolightNoCullGeometryMaterial		L"../BuiltIn/NolightNoCullGeometryMaterial.material"
#define BuiltInGeometryLastMaterial					L"../BuiltIn/GeometryLastMaterial.material"
#define BuiltInNolightGeometryLastMaterial			L"../BuiltIn/NolightGeometryLastMaterial.material"
#define BuiltInAlphaTestMaterial					L"../BuiltIn/AlphaTestMaterial.material"
#define BuiltInNolightAlphaTestMaterial				L"../BuiltIn/NolightAlphaTestMaterial.material"
#define BuiltInTransparentMaterial					L"../BuiltIn/TransparentMaterial.material"
#define BuiltInNolightTransparentMaterial			L"../BuiltIn/NolightTransparentMaterial.material"
#define BuiltInOverlayMaterial						L"../BuiltIn/OverlayMaterial.material"
#define BuiltInLightOverlayMaterial					L"../BuiltIn/LightOverlayMaterial.material"
